# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
acunetix_scan_job:
    runs-on: ubuntu-20.04
    steps:
      # Starts actions with given inputs
      - name: Start Acunetix 360 Scan
        uses: Acunetix360/Acunetix-360-GitHub-Actions@v0.0.1
        id: acunetix-360-scan-step
        with:
          website-id: '0c22bfb3-10bc-45af-98e0-acf3027e9885'
          scan-type: 'FullWithPrimaryProfile'
          profile-id: '00000000-0000-0000-0000-000000000000'
          user-id: ${{ secrets.ACUNETIX_USER_ID }}
          api-token: ${{ secrets.ACUNETIX_API_TOKEN }}
          base-url: 'https://online.acunetix360.com'
      # Displays output for action
      - name: Display Scan Request Message
        run: echo "${{ steps.acunetix-360-scan-step.outputs.scan-message }}"
